# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dshchur/homework/csce_436_shchur/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_xbar_0/skrach_design_xbar_0.xci
# IP: The module: 'skrach_design_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dshchur/homework/csce_436_shchur/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_xbar_0/skrach_design_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'skrach_design_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/dshchur/homework/csce_436_shchur/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_xbar_0/skrach_design_xbar_0.xci
# IP: The module: 'skrach_design_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dshchur/homework/csce_436_shchur/final/code/Skrach.srcs/sources_1/bd/skrach_design/ip/skrach_design_xbar_0/skrach_design_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'skrach_design_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
